namespace Carotte;

/// <summary>
/// Resolves message types and their identifiers for serialization, routing, and dispatching.
/// </summary>
/// <remarks>
/// ⚠️ <b>Important:</b> Producers (publishers) and consumers that exchange messages must use the same (or compatible)
/// <see cref="IMessageTypeResolver"/> implementation. The type identifier generated by <see cref="GetTypeIdentifier"/>
/// during message publication is used by <see cref="ResolveType"/> on the consumer side to resolve and dispatch the message.
/// </remarks>
public interface IMessageTypeResolver
{
    /// <summary>
    /// Gets the type identifier for the specified message type to be stamped on outgoing messages (e.g., in RabbitMQ <c>BasicProperties.Type</c>).
    /// </summary>
    /// <param name="messageType">The CLR type of the message.</param>
    /// <returns>A string identifier representing the message type.</returns>
    string GetTypeIdentifier(Type messageType);

    /// <summary>
    /// Resolves the corresponding CLR type from an incoming type identifier among candidate handled types.
    /// </summary>
    /// <param name="typeIdentifier">The incoming type identifier from message headers/properties.</param>
    /// <param name="candidateTypes">The candidate message types supported by the consumer.</param>
    /// <returns>The resolved <see cref="Type"/>, or <c>null</c> if no matching type is found.</returns>
    Type? ResolveType(string? typeIdentifier, IEnumerable<Type>? candidateTypes);
}
