<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Carotte.Documentation.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Carotte.Documentation\Carotte.Documentation.csproj" />
  </ItemGroup>

</Project>
